### PR TITLE
Add script for getting transitivities from Selventa

### PR DESCRIPTION
**Pull request by cthoyt**
This PR adds the script that downloads/parses the Selventa large corpus and extracts the nested statements.

## Tasks

- [x] Automate caching with pystow
- [x] Normalize names to identifiers

### CODE REVIEW

**Comment by cthoyt** [comment]
@steppi read for review

**Review by steppi — COMMENTED** [review]
Indralab style is to rebase onto main rather than merging main into the feature branch

**Comment by cthoyt** [comment]
@steppi somehow when you force-pushed, some weird things happened and code was lost :/

**Comment by steppi** [comment]
Oh no, sorry. I guess maybe it doesn't actually work to rebase the feature branch on main at the end even if one had previously merged main into the feature branch. Things looked OK on gitk but I didn't actually check that things were OK with the code itself.

**Pull request merged**
